# Generated by Django 2.1.2 on 2018-10-08 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('run', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero', models.IntegerField(verbose_name=9)),
                ('region', models.TextField(max_length=30)),
                ('ciudad', models.TextField(max_length=30)),
                ('vivienda', models.TextField(max_length=30)),
                ('fecha_listar', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
