# Generated by Django 2.1.2 on 2018-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
