# Generated by Django 2.1.2 on 2018-10-08 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181008_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='fecha_listar',
        ),
        migrations.AddField(
            model_name='postulante',
            name='fecha_Nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postulante',
            name='fecha_de_ahora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='region',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='vivienda',
            field=models.CharField(max_length=30),
        ),
    ]
